export const CONVERSATION_CREATED = "CONVERSATION_CREATED";
export const CONVERSATION_UPDATED = "CONVERSATION_UPDATED";
export const CONVERSATION_DELETED = "CONVERSATION_DELETED";

export const MESSAGE_CREATED = "MESSAGE_CREATED";
